"""
Assistify — Multi-Platform Daily Poster
Posts 1 video per day at 19:00 Berlin to Instagram + Facebook + TikTok
Railway hosted, Cloudinary queue
"""

import os
import time
import json
import threading
import requests
from datetime import datetime
from flask import Flask, jsonify
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
import pytz
import cloudinary
import cloudinary.api
import cloudinary.uploader

app = Flask(__name__)
BERLIN = pytz.timezone("Europe/Berlin")

# ─── CONFIG ───────────────────────────────────────────────────────────────────
IG_TOKEN          = os.environ.get("INSTAGRAM_ACCESS_TOKEN", "")
IG_USER_ID        = os.environ.get("INSTAGRAM_USER_ID", "26327994056810336")
FB_PAGE_TOKEN     = os.environ.get("FB_PAGE_ACCESS_TOKEN", "")   # Facebook Page Token
FB_PAGE_ID        = os.environ.get("FB_PAGE_ID", "61579625669890")
TIKTOK_TOKEN      = os.environ.get("TIKTOK_ACCESS_TOKEN", "")    # TikTok Token
TIKTOK_CLIENT_KEY = os.environ.get("TIKTOK_CLIENT_KEY", "")
TIKTOK_CLIENT_SECRET = os.environ.get("TIKTOK_CLIENT_SECRET", "")
LOCATION_ID       = "107681779263786"   # Freiburg im Breisgau
LOCATION_ID_2     = "110953905611108"   # Abu Dhabi, UAE

CLOUDINARY_CLOUD  = os.environ.get("CLOUDINARY_CLOUD_NAME", "dlv8ebddq")
CLOUDINARY_KEY    = os.environ.get("CLOUDINARY_API_KEY", "837591974475139")
CLOUDINARY_SECRET = os.environ.get("CLOUDINARY_API_SECRET", "1wHQz08D45SYbFg7vuecfVMaOac")

CAPTION_IG = """Deine Konkurrenz nutzt bereits KI für ihre Marketing-Videos. 👀

——

🏢 Du willst auch bessere, spezialisierte Videos für dein Business?
→ Schreib uns eine DM oder trag dich in die Warteliste ein:
assistifyai-official.netlify.app/#waitlist

🎬 Du willst ähnliche Videos selbst erstellen?
→ Kommentiere "KI" für eine kostenlose Schritt-für-Schritt-Anleitung

——

#kimarketing #kivideo #ugcvideo #contentcreator #digitalmarketing
#videomarketing #contentmarketing #brandvideo #ugccreator #kitools
#videowerbung #socialmediamarketing #marketingagentur #contentcreation #reels
#kicontent #videoproduktion #marketingtipps #unternehmenswachstum #startupmarketing"""

CAPTION_FB = CAPTION_IG

CAPTION_IG_2 = """Your competitors are already using AI for their marketing videos. 👀

——

🏢 Want better, specialized videos for your business?
→ DM us or join the waitlist:
assistifyai-official.netlify.app/#waitlist

🎬 Want to create similar videos yourself?
→ Comment "AI" for a free step-by-step guide

——

#aimarketing #aivideo #ugcvideo #contentcreator #digitalmarketing
#videomarketing #contentmarketing #brandvideo #ugccreator #aitools
#videoads #socialmediamarketing #marketingagency #contentcreation #reels
#aicontentcreation #videoproduction #marketingtips #businessgrowth #startupmarketing"""

CAPTION_FB_2 = CAPTION_IG_2

CAPTION_TT = """Your competitors are already using AI for their marketing videos. 👀

🏢 Want videos for your business? DM us or join the waitlist → link in bio
🎬 Want to make these yourself? Comment "AI" for a free guide

#aimarketing #aivideo #ugcvideo #contentcreator #digitalmarketing
#videomarketing #contentmarketing #brandvideo #ugccreator #aitools
#videoads #socialmediamarketing #marketingagency #contentcreation #reels"""

CAPTION_IG_3 = """This video was made with AI. 🤖🎬

——

Every frame. Every scene. 100% AI-generated storytelling.
This is what we build for brands at Assistify AI.

💡 Want a free AI video for your business?
→ Comment "AI" and we'll send you everything you need

——

#aivideo #aimarketing #aigeneratedvideo #storytellingmarketing #contentcreator
#digitalmarketing #videomarketing #brandvideo #aitools #contentcreation
#reels #socialmediamarketing #marketingagency #businessgrowth #aicontentcreation"""

CAPTION_FB_3 = CAPTION_IG_3

# ─── Per-video captions for Queue 3 ──────────────────────────────────────────
CAPTIONS_Q3 = {
    "ig_queue_3/01_EN": """The future of brand storytelling is here. 🎬✨

——

We created this entire scene using AI — no camera, no crew, no studio.
Just a vision, the right tools, and Assistify AI.

💡 Want a cinematic AI video for your brand?
→ Comment "AI" — we'll send you the full guide for free
→ Or visit: assistifyai-official.netlify.app

——

#aivideo #aifilmmaking #aigeneratedvideo #brandstorytelling #contentcreator
#digitalmarketing #videomarketing #aimarketing #aitools #reels
#contentcreation #marketingagency #businessgrowth #aicontentcreation #futureofmarketing""",

    "ig_queue_3/02_EN": """What if your brand had its own cinematic universe? 🌍🎥

——

Every frame in this video was generated by AI.
No actors. No location. Just pure visual storytelling.
This is the power we bring to your brand at Assistify AI.

💡 Ready to stand out?
→ Comment "AI" for a free step-by-step guide
→ Or visit: assistifyai-official.netlify.app

——

#aicinema #aigeneratedcontent #brandvideo #aistorytelling #contentmarketing
#reels #videomarketing #aimarketing #digitalmarketing #ugcvideo
#socialmediamarketing #aitools #contentcreation #marketingagency #businessgrowth""",

    "ig_queue_3/03_EN": """This isn't a movie trailer. This is AI. 🤖🎞️

——

We're building cinematic brand experiences using AI — faster, cheaper, and more creative than traditional production.
Assistify AI turns your brand story into a visual masterpiece.

💡 Want this for your business?
→ Comment "AI" and we'll show you how
→ assistifyai-official.netlify.app

——

#aimarketing #aigeneratedvideo #filmmaking #contentcreator #brandstorytelling
#videomarketing #reels #aitools #digitalmarketing #socialmediamarketing
#contentcreation #marketingagency #ugcvideo #aicinema #businessgrowth""",

    "ig_queue_3/04_EN": """Hollywood quality. Zero budget. 100% AI. 🏆🎬

——

AI has completely changed what's possible in video production.
What used to take months and thousands of euros now takes hours.
We make this happen for brands at Assistify AI.

💡 Want cinematic AI content for your brand?
→ Comment "AI" for the free guide
→ Or join the waitlist: assistifyai-official.netlify.app/#waitlist

——

#aivideo #aiproduction #hollywoodstyle #contentcreator #brandvideo
#videomarketing #aimarketing #reels #digitalmarketing #ugcvideo
#socialmediamarketing #aitools #contentcreation #aicinema #futureofmarketing""",

    "ig_queue_3/05_EN": """Your competitors are sleeping on this. 👀🎥

——

AI-generated storytelling is the biggest shift in content marketing right now.
Early movers will dominate their market.
We help brands get there — with Assistify AI.

💡 Want to be ahead of the curve?
→ Comment "AI" for your free video guide
→ assistifyai-official.netlify.app

——

#aimarketing #aigeneratedvideo #contentmarketing #brandstorytelling #reels
#videomarketing #aitools #digitalmarketing #socialmediamarketing #contentcreator
#businessgrowth #marketingagency #aicontentcreation #ugcvideo #futurism""",

    "ig_queue_3/06_EN": """This scene was never filmed. It was imagined — and then built by AI. 🌌🎞️

——

No green screen. No crew. No post-production team.
Just AI, creativity, and a clear brand vision.
At Assistify AI, we turn ideas into cinematic reality.

💡 Want a free AI video for your brand?
→ Comment "AI" and we'll send you everything
→ assistifyai-official.netlify.app

——

#aifilmmaking #aigeneratedcontent #brandvideo #aistorytelling #contentcreator
#reels #videomarketing #aimarketing #digitalmarketing #aitools
#socialmediamarketing #contentcreation #marketingagency #businessgrowth #aicinema""",

    "ig_queue_3/07_EN": """The line between real and AI is fading. Fast. 🎬🤯

——

Every detail in this video — lighting, movement, atmosphere — generated entirely by AI.
This is where marketing is heading.
And we're already there at Assistify AI.

💡 Get ahead of the wave:
→ Comment "AI" for a free guide to AI video creation
→ assistifyai-official.netlify.app

——

#aivideo #aimarketing #aigeneratedvideo #futureofmarketing #contentcreator
#brandvideo #videomarketing #reels #digitalmarketing #aitools
#socialmediamarketing #contentcreation #marketingagency #aicinema #businessgrowth""",

    "ig_queue_3/01_ST": """Cinematic. Emotional. 100% AI-generated. 🎬❤️

——

Every frame of this video was created using artificial intelligence.
No camera. No crew. Just pure storytelling.
This is what Assistify AI builds for brands like yours.

💡 Want your own AI cinematic video?
→ Comment "AI" — we'll send you a full guide for free
→ assistifyai-official.netlify.app

——

#aistorytelling #aicinema #aigeneratedvideo #brandvideo #contentcreator
#videomarketing #aimarketing #reels #digitalmarketing #aitools
#contentcreation #socialmediamarketing #marketingagency #businessgrowth #futureofmarketing""",

    "ig_queue_3/02_ST": """AI doesn't just make content — it tells stories. 📖🤖

——

We're entering an era where brands can have their own AI-generated film universe.
Every emotion. Every scene. Crafted with precision by AI.
Assistify AI is your creative partner in this new world.

💡 Ready to tell your brand's story?
→ Comment "AI" for a free step-by-step guide
→ assistifyai-official.netlify.app

——

#aistorytelling #aigeneratedcontent #brandstorytelling #contentmarketing #reels
#videomarketing #aimarketing #aitools #digitalmarketing #contentcreator
#socialmediamarketing #marketingagency #businessgrowth #aicontentcreation #aicinema""",

    "ig_queue_3/03_ST": """Hollywood visuals. AI speed. Zero compromise. 🏆✨

——

What you're watching was made entirely with AI — in a fraction of the time and cost of traditional production.
This is the new standard for brand video content.
We bring it to you at Assistify AI.

💡 Want this for your brand?
→ Comment "AI" for our free AI video guide
→ Or visit: assistifyai-official.netlify.app

——

#aivideo #aifilm #aigeneratedvideo #brandvideo #contentcreator
#videomarketing #aimarketing #reels #digitalmarketing #aitools
#socialmediamarketing #contentcreation #marketingagency #aicinema #businessgrowth""",

    "ig_queue_3/04_ST": """What if your brand had its own AI film? 🎥🌟

——

This is exactly what we build at Assistify AI.
Cinematic storytelling, brand-specific, fully AI-generated.
Your audience won't just watch — they'll remember.

💡 Get your free AI video:
→ Comment "AI" and we'll send you the guide
→ assistifyai-official.netlify.app/#waitlist

——

#aistorytelling #brandfilm #aigeneratedvideo #contentmarketing #reels
#videomarketing #aimarketing #contentcreator #digitalmarketing #aitools
#socialmediamarketing #marketingagency #businessgrowth #aicinema #ugcvideo""",

    "ig_queue_3/05_ST": """AI storytelling is the new marketing frontier. 🚀🎬

——

Brands that invest in AI-generated video content today will dominate tomorrow.
Every scene in this video was built by AI — and it took a fraction of traditional production time.
Assistify AI is your shortcut to the future.

💡 Be an early mover:
→ Comment "AI" for a free video guide
→ assistifyai-official.netlify.app

——

#aimarketing #aigeneratedcontent #futureofmarketing #brandstorytelling #reels
#contentcreator #videomarketing #aitools #digitalmarketing #businessgrowth
#socialmediamarketing #contentcreation #marketingagency #aicinema #aivideo""",

    "ig_queue_3/06_ST": """We built this from nothing. Just AI and imagination. 🌌🎞️

——

No set. No actors. No production team.
Just a concept — and AI powerful enough to bring it to life.
This is what Assistify AI does for brands every day.

💡 Want to see what we'd create for your brand?
→ Comment "AI" — we'll send everything you need
→ assistifyai-official.netlify.app

——

#aistorytelling #aifilmmaking #aigeneratedvideo #brandvideo #contentcreator
#videomarketing #aimarketing #reels #digitalmarketing #aitools
#socialmediamarketing #contentcreation #marketingagency #businessgrowth #aicinema""",

    "ig_queue_3/07_ST": """AI filmmaking at its finest. 🎬🤯

——

The atmosphere. The lighting. The movement. All AI.
This is not the future — this is now.
And brands using AI video content are already winning.
Assistify AI helps you win too.

💡 Start creating with AI today:
→ Comment "AI" for your free guide
→ assistifyai-official.netlify.app

——

#aivideo #aicinema #aigeneratedvideo #brandstorytelling #contentcreator
#videomarketing #aimarketing #reels #digitalmarketing #aitools
#socialmediamarketing #contentcreation #marketingagency #businessgrowth #futureofmarketing""",

    "ig_queue_3/08_ST": """The story was written by humans. Filmed entirely by AI. 📝🤖

——

AI is no longer just a tool — it's a creative collaborator.
We combine human vision with AI precision to create content that stops the scroll.
That's the Assistify AI difference.

💡 Ready to create something unforgettable?
→ Comment "AI" and we'll guide you step by step
→ assistifyai-official.netlify.app

——

#aistorytelling #aigeneratedcontent #humanplusai #brandvideo #contentcreator
#videomarketing #aimarketing #reels #digitalmarketing #contentcreation
#socialmediamarketing #marketingagency #aitools #businessgrowth #aicinema""",

    "ig_queue_3/09_ST": """AI can now create emotions on screen. 🎭✨

——

What you feel watching this — that's the power of AI storytelling.
Brands that connect emotionally with their audience win every time.
Assistify AI helps you build that connection through AI-generated film.

💡 Want to connect with your audience like this?
→ Comment "AI" for a free video guide
→ assistifyai-official.netlify.app

——

#aistorytelling #emotionalmarketing #aigeneratedvideo #brandvideo #contentcreator
#videomarketing #aimarketing #reels #digitalmarketing #aitools
#contentcreation #socialmediamarketing #marketingagency #businessgrowth #aicinema""",

    "ig_queue_3/10_ST": """Every single second of this was generated by AI. ⏱️🎬

——

Not one frame was captured by a camera.
Not one actor stood in front of a lens.
This is the new reality of content production — and it's available to your brand right now.

💡 Want AI video for your business?
→ Comment "AI" for the free guide
→ assistifyai-official.netlify.app

——

#aivideo #aigeneratedvideo #aiproduction #brandvideo #contentcreator
#videomarketing #aimarketing #reels #digitalmarketing #aitools
#socialmediamarketing #contentcreation #marketingagency #businessgrowth #futureofmarketing""",

    "ig_queue_3/11_ST": """The era of AI cinema has officially begun. 🌅🎥

——

We are living through the biggest creative revolution in history.
AI can now produce cinematic content that moves people — and moves brands forward.
Assistify AI is at the forefront of this revolution.

💡 Join the revolution:
→ Comment "AI" for your free step-by-step guide
→ assistifyai-official.netlify.app/#waitlist

——

#aicinema #aigeneratedcontent #creativerevolution #brandstorytelling #contentcreator
#videomarketing #aimarketing #reels #digitalmarketing #aitools
#socialmediamarketing #contentcreation #marketingagency #businessgrowth #futureofmarketing""",

    "ig_queue_3/12_ST": """Your competitors haven't discovered this yet. 🕵️🚀

——

AI-generated storytelling videos are still the secret weapon of early-mover brands.
The window to stand out is open — but not forever.
Assistify AI gives you the edge before everyone else catches up.

💡 Claim your advantage now:
→ Comment "AI" — we'll send you the full guide
→ assistifyai-official.netlify.app

——

#aimarketing #earlymovers #aigeneratedvideo #brandvideo #contentcreator
#videomarketing #reels #digitalmarketing #aitools #contentcreation
#socialmediamarketing #marketingagency #businessgrowth #competitiveadvantage #aivideo""",

    "ig_queue_3/13_ST": """We use AI to tell your brand's story — and people can't stop watching. 👁️🎬

——

Scroll-stopping content isn't about budget anymore.
It's about creativity + AI.
At Assistify AI, we combine both to create videos that convert.

💡 See what we'd create for your brand:
→ Comment "AI" for a free guide + consultation
→ assistifyai-official.netlify.app

——

#aistorytelling #brandstorytelling #aigeneratedvideo #contentmarketing #reels
#videomarketing #aimarketing #contentcreator #digitalmarketing #aitools
#socialmediamarketing #contentcreation #marketingagency #businessgrowth #aicinema""",

    "ig_queue_3/14_ST": """The future of brand storytelling is AI. And the future is now. 🔮🎬

——

Every scene. Every emotion. Every visual detail — created by artificial intelligence.
This is what we build for forward-thinking brands at Assistify AI.
The question is: will your brand be part of this future?

💡 Let's create something incredible together:
→ Comment "AI" for a free video guide
→ assistifyai-official.netlify.app
→ Follow us for daily AI content 💡

——

#aistorytelling #aigeneratedvideo #futureofmarketing #brandvideo #contentcreator
#videomarketing #aimarketing #reels #digitalmarketing #aitools
#socialmediamarketing #contentcreation #marketingagency #businessgrowth #aicinema""",

    "ig_queue_3/video_1234": """Nature meets AI. The most powerful combination in modern storytelling. 🌿🤖

——

Four stunning AI-generated scenes, seamlessly woven into one cinematic experience.
This is what we create for brands at Assistify AI — content that stops the scroll.

💡 Want a free AI video for your business?
→ Comment "AI" and we'll send you everything
→ assistifyai-official.netlify.app

——

#aivideo #aistorytelling #naturevideo #aigeneratedvideo #contentcreator
#videomarketing #aimarketing #reels #digitalmarketing #aitools
#socialmediamarketing #contentcreation #marketingagency #businessgrowth #aicinema""",

    "ig_queue_3/video_56": """Two worlds. One AI vision. Completely breathtaking. 🎬🌍

——

These scenes were never filmed — they were imagined and built entirely by AI.
At Assistify AI, we turn creative visions into cinematic brand moments.

💡 Ready to create something unforgettable?
→ Comment "AI" for a free step-by-step guide
→ assistifyai-official.netlify.app/#waitlist

——

#aigeneratedvideo #aicinema #brandstorytelling #contentcreator #videomarketing
#aimarketing #reels #digitalmarketing #aitools #contentcreation
#socialmediamarketing #marketingagency #businessgrowth #aivideo #futureofmarketing""",

    "ig_queue_3/video_a": """The AI revolution in content creation is already here. 🤖⚡

——

Futuristic. Fast. Powerful. This is what AI-generated brand content looks like in 2025.
Assistify AI builds this for your brand — no camera, no crew, no limits.

💡 Want AI content for your business?
→ Comment "AI" — free guide in your DMs
→ assistifyai-official.netlify.app

——

#aivideo #aimarketing #futureofmarketing #contentcreator #digitalmarketing
#videomarketing #aitools #reels #brandvideo #contentcreation
#socialmediamarketing #marketingagency #businessgrowth #aicontentcreation #aicinema""",

    "ig_queue_3/video_b": """AI doesn't just create content — it creates worlds. 🌐🎥

——

Every visual, every detail, every moment — crafted by artificial intelligence.
This is the kind of brand content that makes people stop, watch, and remember.
Assistify AI makes it happen for you.

💡 Want your brand to look like this?
→ Comment "AI" for a free video guide
→ assistifyai-official.netlify.app

——

#aigeneratedvideo #aicinema #brandvideo #contentcreator #videomarketing
#aimarketing #reels #digitalmarketing #aitools #contentcreation
#socialmediamarketing #marketingagency #businessgrowth #aistorytelling #futurism""",

    "ig_queue_3/video_c": """Real stories. AI visuals. Zero compromise. 🎞️✨

——

The best storytelling combines authentic emotion with cutting-edge visuals.
At Assistify AI, we bring both together for brands who want to stand out.

💡 Want this for your brand?
→ Comment "AI" and we'll show you how
→ assistifyai-official.netlify.app

——

#aivideo #brandstorytelling #aigeneratedcontent #contentcreator #videomarketing
#aimarketing #reels #digitalmarketing #aitools #contentcreation
#socialmediamarketing #marketingagency #businessgrowth #aicinema #ugcvideo""",

    "ig_queue_3/video_d": """Vertical. Cinematic. 100% AI-generated. 📱🎬

——

Mobile-first content that doesn't sacrifice quality.
Every frame of this video was built by AI — optimized for the way people actually consume content today.
This is Assistify AI.

💡 Get your free AI video guide:
→ Comment "AI" right now
→ assistifyai-official.netlify.app/#waitlist

——

#aivideo #mobilecontent #aigeneratedvideo #contentcreator #videomarketing
#aimarketing #reels #digitalmarketing #aitools #contentcreation
#socialmediamarketing #marketingagency #businessgrowth #aicinema #brandvideo""",

    "ig_queue_3/video_e": """Epic. Dramatic. Built entirely by AI. 🏆🎬

——

This is the new standard for brand video production.
No studio. No budget limitations. Just pure AI creativity at its finest.
Assistify AI delivers this level of quality for every client.

💡 Ready to elevate your brand?
→ Comment "AI" for a free consultation
→ assistifyai-official.netlify.app

——

#epicvideo #aicinema #aigeneratedvideo #brandvideo #contentcreator
#videomarketing #aimarketing #reels #digitalmarketing #aitools
#socialmediamarketing #contentcreation #marketingagency #businessgrowth #aivideo""",

    "ig_queue_3/video_ttt": """Good morning. This video was made with AI. ☀️🎸

——

Start your day with something beautiful — and a reminder of what AI can create.
At Assistify AI, we craft morning-worthy content that your audience will love.

💡 Want content like this for your brand?
→ Comment "AI" for a free guide
→ assistifyai-official.netlify.app

——

#morningvibes #aivideo #aigeneratedvideo #contentcreator #videomarketing
#aimarketing #reels #digitalmarketing #aitools #contentcreation
#socialmediamarketing #marketingagency #businessgrowth #goodmorning #aicinema""",

    "ig_queue_3/video_w": """Wide. Cinematic. Completely AI. 🎥🌅

——

Widescreen storytelling, crafted entirely by artificial intelligence.
No location. No production crew. Just vision — and the power of AI.
Assistify AI brings this to your brand.

💡 Comment "AI" for a free video for your business
→ assistifyai-official.netlify.app

——

#cinematicvideo #aigeneratedvideo #aivideo #contentcreator #videomarketing
#aimarketing #reels #digitalmarketing #aitools #contentcreation
#socialmediamarketing #marketingagency #businessgrowth #aicinema #brandvideo""",

    "ig_queue_3/video_ww": """Short. Powerful. 100% AI-generated. ⚡🎬

——

Even in just a few seconds, AI can tell a complete brand story.
This is the future of short-form content — and it's available to your brand right now.

💡 Want AI short-form content for your business?
→ Comment "AI" for everything you need
→ assistifyai-official.netlify.app

——

#shortformcontent #aivideo #aigeneratedvideo #contentcreator #videomarketing
#aimarketing #reels #digitalmarketing #aitools #contentcreation
#socialmediamarketing #marketingagency #businessgrowth #aicinema #brandvideo""",

    "ig_queue_3/video_www": """Eight seconds of pure AI magic. 🪄🎬

——

Every moment of this video was created by artificial intelligence.
No camera ever captured this scene — it exists only because AI made it real.
This is what Assistify AI does for brands every single day.

💡 Let's create your AI video:
→ Comment "AI" for a free guide
→ assistifyai-official.netlify.app

——

#aivideo #aimagic #aigeneratedvideo #contentcreator #videomarketing
#aimarketing #reels #digitalmarketing #aitools #contentcreation
#socialmediamarketing #marketingagency #businessgrowth #aicinema #brandstorytelling""",

    "ig_queue_3/video_x": """Bold. Epic. Viking-level AI storytelling. ⚔️🎬

——

Power. Drama. Atmosphere. All created by artificial intelligence.
When your brand needs content that commands attention — this is what Assistify AI delivers.

💡 Want powerful AI content for your brand?
→ Comment "AI" — free guide waiting for you
→ assistifyai-official.netlify.app

——

#epicvideo #aicinema #aigeneratedvideo #brandvideo #contentcreator
#videomarketing #aimarketing #reels #digitalmarketing #aitools
#socialmediamarketing #contentcreation #marketingagency #businessgrowth #boldcontent""",
}
# ──────────────────────────────────────────────────────────────────────────────

cloudinary.config(
    cloud_name=CLOUDINARY_CLOUD,
    api_key=CLOUDINARY_KEY,
    api_secret=CLOUDINARY_SECRET,
)

def get_next_video(tag="ig_queue"):
    try:
        result = cloudinary.api.resources_by_tag(
            tag, resource_type="video", context=True, max_results=100
        )
        assets = result.get("resources", [])
        unposted = [
            a for a in assets
            if a.get("context", {}).get("custom", {}).get("ig_posted") == "false"
        ]
        if not unposted:
            return None
        unposted.sort(key=lambda x: int(x.get("context", {}).get("custom", {}).get("post_order", 999)))
        return unposted[0]
    except Exception as e:
        print(f"Cloudinary Fehler: {e}")
        return None

def post_instagram(video_url: str) -> bool:
    if not IG_TOKEN:
        print("Instagram: kein Token")
        return False

    base = f"https://graph.instagram.com/v21.0/{IG_USER_ID}"
    print("Instagram: Erstelle Container...")

    r = requests.post(f"{base}/media", data={
        "video_url":     video_url,
        "media_type":    "REELS",
        "caption":       CAPTION_IG,
        "share_to_feed": "true",
        "thumb_offset":  "1000",
        "access_token":  IG_TOKEN,
    })
    if r.status_code != 200:
        print(f"Instagram Container-Fehler: {r.text}")
        return False

    container_id = r.json().get("id")
    print(f"Instagram Container: {container_id} — warte auf Verarbeitung...")

    for attempt in range(20):
        time.sleep(15)
        s = requests.get(
            f"https://graph.instagram.com/v21.0/{container_id}",
            params={"fields": "status_code", "access_token": IG_TOKEN}
        ).json().get("status_code", "")
        print(f"  Status: {s} ({attempt+1}/20)")
        if s == "FINISHED":
            break
        if s == "ERROR":
            print("Instagram: Verarbeitung fehlgeschlagen")
            return False

    pub = requests.post(f"{base}/media_publish", data={
        "creation_id": container_id,
        "access_token": IG_TOKEN,
    })
    if pub.status_code == 200:
        print(f"Instagram: Gepostet! ID: {pub.json().get('id')}")
        return True
    print(f"Instagram Publish-Fehler: {pub.text}")
    return False

def post_instagram_2(video_url: str) -> bool:
    if not IG_TOKEN:
        print("Instagram: kein Token")
        return False

    base = f"https://graph.instagram.com/v21.0/{IG_USER_ID}"
    print("Instagram (Queue 2): Erstelle Container...")

    data = {
        "video_url":     video_url,
        "media_type":    "REELS",
        "caption":       CAPTION_IG_2,
        "share_to_feed": "true",
        "thumb_offset":  "1000",
        "access_token":  IG_TOKEN,
    }

    r = requests.post(f"{base}/media", data=data)
    if r.status_code != 200:
        print(f"Instagram Container-Fehler: {r.text}")
        return False

    container_id = r.json().get("id")
    print(f"Instagram Container: {container_id} — warte auf Verarbeitung...")

    for attempt in range(20):
        time.sleep(15)
        s = requests.get(
            f"https://graph.instagram.com/v21.0/{container_id}",
            params={"fields": "status_code", "access_token": IG_TOKEN}
        ).json().get("status_code", "")
        print(f"  Status: {s} ({attempt+1}/20)")
        if s == "FINISHED":
            break
        if s == "ERROR":
            print("Instagram: Verarbeitung fehlgeschlagen")
            return False

    pub = requests.post(f"{base}/media_publish", data={
        "creation_id": container_id,
        "access_token": IG_TOKEN,
    })
    if pub.status_code == 200:
        print(f"Instagram (Queue 2): Gepostet! ID: {pub.json().get('id')}")
        return True
    print(f"Instagram Publish-Fehler: {pub.text}")
    return False

def post_facebook_2(video_url: str) -> bool:
    if not FB_PAGE_TOKEN:
        print("Facebook: kein Page Token — übersprungen")
        return False

    print("Facebook (Queue 2): Poste Video...")
    r = requests.post(
        f"https://graph-video.facebook.com/v21.0/{FB_PAGE_ID}/videos",
        data={
            "file_url":    video_url,
            "description": CAPTION_FB_2,
            "published":   "true",
            "access_token": FB_PAGE_TOKEN,
        }
    )
    if r.status_code == 200:
        print(f"Facebook (Queue 2): Gepostet! ID: {r.json().get('id')}")
        return True
    print(f"Facebook Fehler: {r.text}")
    return False

def post_facebook(video_url: str, published: bool = True) -> bool:
    if not FB_PAGE_TOKEN:
        print("Facebook: kein Page Token — übersprungen")
        return False

    print(f"Facebook: Poste Video (published={published})...")
    r = requests.post(
        f"https://graph-video.facebook.com/v21.0/{FB_PAGE_ID}/videos",
        data={
            "file_url":    video_url,
            "description": CAPTION_FB,
            "published":   "true" if published else "false",
            "access_token": FB_PAGE_TOKEN,
        }
    )
    if r.status_code == 200:
        print(f"Facebook: Gepostet! ID: {r.json().get('id')}")
        return True
    print(f"Facebook Fehler: {r.text}")
    return False

def post_tiktok(video_url: str) -> bool:
    if not TIKTOK_TOKEN:
        print("TikTok: kein Token — übersprungen")
        return False

    print(f"TikTok: Token Länge: {len(TIKTOK_TOKEN)} | Anfang: {TIKTOK_TOKEN[:20]}")
    print("TikTok: Poste Video...")
    # TikTok Content Posting API v2
    r = requests.post(
        "https://open.tiktokapis.com/v2/post/publish/video/init/",
        headers={
            "Authorization": f"Bearer {TIKTOK_TOKEN}",
            "Content-Type": "application/json; charset=UTF-8",
        },
        json={
            "post_info": {
                "title": CAPTION_TT[:150],
                "privacy_level": "PUBLIC_TO_EVERYONE",
                "disable_duet": False,
                "disable_comment": False,
                "disable_stitch": False,
            },
            "source_info": {
                "source": "PULL_FROM_URL",
                "video_url": video_url,
            }
        }
    )
    if r.status_code == 200:
        print(f"TikTok: Upload gestartet! {r.json()}")
        return True
    print(f"TikTok Fehler: {r.text}")
    return False

def mark_as_posted(public_id: str):
    try:
        cloudinary.uploader.explicit(
            public_id, type="upload", resource_type="video",
            context=f"ig_posted=true|posted_at={datetime.now(BERLIN).strftime('%Y-%m-%d %H:%M')}",
        )
    except Exception as e:
        print(f"Marking-Fehler: {e}")

def daily_post():
    now = datetime.now(BERLIN)
    print(f"\n{'='*50}")
    print(f"Daily Post 19:00 (Freiburg): {now.strftime('%d.%m.%Y %H:%M')} Berlin")
    print(f"{'='*50}")

    video = get_next_video("ig_queue")
    if not video:
        print("Queue leer — keine Videos mehr!")
        return

    video_url = video.get("secure_url")
    public_id = video.get("public_id")
    order = video.get("context", {}).get("custom", {}).get("post_order", "?")
    print(f"Video #{order}: {public_id}\n")

    ig_ok = post_instagram(video_url)
    time.sleep(5)
    fb_ok = post_facebook(video_url)
    time.sleep(5)
    tt_ok = post_tiktok(video_url)

    print(f"\nErgebnis: Instagram={'✓' if ig_ok else '✗'} | Facebook={'✓' if fb_ok else '✗'} | TikTok={'✓' if tt_ok else '✗'}")

    if ig_ok or fb_ok or tt_ok:
        mark_as_posted(public_id)

def daily_post_noon():
    now = datetime.now(BERLIN)
    print(f"\n{'='*50}")
    print(f"Daily Post 12:00 (Abu Dhabi): {now.strftime('%d.%m.%Y %H:%M')} Berlin")
    print(f"{'='*50}")

    video = get_next_video("ig_queue_2")
    if not video:
        print("Queue 2 leer — keine Videos mehr!")
        return

    video_url = video.get("secure_url")
    public_id = video.get("public_id")
    order = video.get("context", {}).get("custom", {}).get("post_order", "?")
    print(f"Video #{order}: {public_id}\n")

    # Post Instagram with Abu Dhabi location
    ig_ok = post_instagram_2(video_url)
    time.sleep(5)
    fb_ok = post_facebook_2(video_url)

    print(f"\nErgebnis: Instagram={'✓' if ig_ok else '✗'} | Facebook={'✓' if fb_ok else '✗'}")

    if ig_ok or fb_ok:
        mark_as_posted(public_id)

def post_instagram_3(video_url: str, caption: str) -> bool:
    """Queue 3 — 20:00 Berlin, Storytelling EN"""
    if not IG_TOKEN:
        print("Instagram: kein Token")
        return False
    print("Instagram (Queue 3 Storytelling): Erstelle Container...")
    r = requests.post(
        f"https://graph.instagram.com/v21.0/{IG_USER_ID}/media",
        data={
            "media_type":    "REELS",
            "video_url":     video_url,
            "caption":       caption,
            "share_to_feed": "true",
            "thumb_offset":  "1000",
            "access_token":  IG_TOKEN,
        }
    )
    if r.status_code != 200:
        print(f"Container-Fehler: {r.text}")
        return False
    container_id = r.json().get("id")
    print(f"Instagram Container: {container_id} — warte auf Verarbeitung...")
    for attempt in range(20):
        time.sleep(15)
        s = requests.get(
            f"https://graph.instagram.com/v21.0/{container_id}",
            params={"fields": "status_code", "access_token": IG_TOKEN}
        ).json().get("status_code", "")
        print(f"  Status: {s} ({attempt+1}/20)")
        if s == "FINISHED":
            break
        if s == "ERROR":
            print("Instagram: Verarbeitung fehlgeschlagen")
            return False
    pub = requests.post(
        f"https://graph.instagram.com/v21.0/{IG_USER_ID}/media_publish",
        data={"creation_id": container_id, "access_token": IG_TOKEN}
    )
    if pub.status_code == 200:
        print(f"Instagram (Queue 3): Gepostet! ID: {pub.json().get('id')}")
        return True
    print(f"Instagram Publish-Fehler: {pub.text}")
    return False

def post_facebook_3(video_url: str, caption: str) -> bool:
    """Queue 3 — 20:00 Berlin, Storytelling EN"""
    if not FB_PAGE_TOKEN:
        print("Facebook: kein Page Token — übersprungen")
        return False
    print("Facebook (Queue 3 Storytelling): Poste Video...")
    r = requests.post(
        f"https://graph-video.facebook.com/v21.0/{FB_PAGE_ID}/videos",
        data={
            "file_url":     video_url,
            "description":  caption,
            "published":    "true",
            "access_token": FB_PAGE_TOKEN,
        }
    )
    if r.status_code == 200:
        print(f"Facebook (Queue 3): Gepostet! ID: {r.json().get('id')}")
        return True
    print(f"Facebook Fehler: {r.text}")
    return False

def daily_post_evening():
    now = datetime.now(BERLIN)
    print(f"\n{'='*50}")
    print(f"Daily Post 20:00 (Storytelling EN): {now.strftime('%d.%m.%Y %H:%M')} Berlin")
    print(f"{'='*50}")

    video = get_next_video("ig_queue_3")
    if not video:
        print("Queue 3 leer — keine Storytelling Videos mehr!")
        return

    video_url = video.get("secure_url")
    public_id = video.get("public_id")
    order = video.get("context", {}).get("custom", {}).get("post_order", "?")
    print(f"Video #{order}: {public_id}\n")

    caption = CAPTIONS_Q3.get(public_id, CAPTION_IG_3)
    print(f"Caption: {caption[:60]}...")

    ig_ok = post_instagram_3(video_url, caption)
    time.sleep(5)
    fb_ok = post_facebook_3(video_url, caption)

    print(f"\nErgebnis: Instagram={'✓' if ig_ok else '✗'} | Facebook={'✓' if fb_ok else '✗'}")

    if ig_ok or fb_ok:
        mark_as_posted(public_id)

# ─── Routes ───────────────────────────────────────────────────────────────────
@app.route("/")
def home():
    return jsonify({"status": "running", "service": "Assistify Multi-Platform Poster"})

@app.route("/post_now")
def post_now():
    threading.Thread(target=daily_post, daemon=True).start()
    return jsonify({"status": "started — check logs"})

@app.route("/post_now_noon")
def post_now_noon():
    threading.Thread(target=daily_post_noon, daemon=True).start()
    return jsonify({"status": "Queue 2 gestartet — check logs"})

@app.route("/post_now_evening")
def post_now_evening():
    threading.Thread(target=daily_post_evening, daemon=True).start()
    return jsonify({"status": "Queue 3 (Storytelling) gestartet — check logs"})

@app.route("/queue3")
def queue3_status():
    try:
        result = cloudinary.api.resources_by_tag("ig_queue_3", resource_type="video", context=True, max_results=100)
        assets = result.get("resources", [])
        unposted = [a for a in assets if a.get("context", {}).get("custom", {}).get("ig_posted") == "false"]
        posted = [a for a in assets if a.get("context", {}).get("custom", {}).get("ig_posted") == "true"]
        return jsonify({"total": len(assets), "noch_ausstehend": len(unposted), "gepostet": len(posted)})
    except Exception as e:
        return jsonify({"error": str(e)})

@app.route("/queue2")
def queue2_status():
    try:
        result = cloudinary.api.resources_by_tag("ig_queue_2", resource_type="video", context=True, max_results=100)
        assets = result.get("resources", [])
        unposted = [a for a in assets if a.get("context", {}).get("custom", {}).get("ig_posted") == "false"]
        posted = [a for a in assets if a.get("context", {}).get("custom", {}).get("ig_posted") == "true"]
        return jsonify({"total": len(assets), "noch_ausstehend": len(unposted), "gepostet": len(posted)})
    except Exception as e:
        return jsonify({"error": str(e)})

@app.route("/find_location_abudhabi")
def find_location_abudhabi():
    token = FB_PAGE_TOKEN or IG_TOKEN
    if not token:
        return jsonify({"error": "Kein Token verfügbar"})
    q = "Abu Dhabi"
    r = requests.get(
        "https://graph.facebook.com/v21.0/search",
        params={"type": "place", "q": q, "fields": "id,name,location", "access_token": token}
    )
    return jsonify(r.json())

@app.route("/test_facebook")
def test_facebook():
    def run():
        video = get_next_video()
        if not video:
            print("Queue leer")
            return
        video_url = video.get("secure_url")
        print(f"Facebook Test mit: {video_url}")
        post_facebook(video_url, published=False)  # Privat / unpublished für Test
    threading.Thread(target=run, daemon=True).start()
    return jsonify({"status": "Facebook Test gestartet — check logs"})

@app.route("/find_location")
def find_location():
    token = FB_PAGE_TOKEN or IG_TOKEN
    if not token:
        return jsonify({"error": "Kein Token verfügbar"})
    q = "Freiburg im Breisgau"
    r = requests.get(
        "https://graph.facebook.com/v21.0/search",
        params={"type": "place", "q": q, "fields": "id,name,location", "access_token": token}
    )
    return jsonify(r.json())

@app.route("/queue")
def queue_status():
    try:
        result = cloudinary.api.resources_by_tag("ig_queue", resource_type="video", context=True, max_results=100)
        assets = result.get("resources", [])
        unposted = [a for a in assets if a.get("context", {}).get("custom", {}).get("ig_posted") == "false"]
        posted = [a for a in assets if a.get("context", {}).get("custom", {}).get("ig_posted") == "true"]
        return jsonify({"total": len(assets), "noch_ausstehend": len(unposted), "gepostet": len(posted)})
    except Exception as e:
        return jsonify({"error": str(e)})

@app.route("/test_tiktok")
def test_tiktok():
    def run():
        video = get_next_video()
        if not video:
            print("Queue leer")
            return
        video_url = video.get("secure_url")
        print(f"TikTok Test mit: {video_url}")
        post_tiktok(video_url)
    threading.Thread(target=run, daemon=True).start()
    return jsonify({"status": "TikTok Test gestartet — check logs"})

@app.route("/tiktokoxDjnNm6ADOs6kJuaXIXlProCPwZX61Q.txt")
def tiktok_verify():
    return "tiktok-developers-site-verification=oxDjnNm6ADOs6kJuaXIXIProCPwZX61Q", 200, {"Content-Type": "text/plain"}

@app.route("/tiktokoxDjnNm6ADOs6kJuaXIXIProCPwZX61Q.txt")
def tiktok_verify2():
    return "tiktok-developers-site-verification=oxDjnNm6ADOs6kJuaXIXIProCPwZX61Q", 200, {"Content-Type": "text/plain"}

@app.route("/terms")
def terms():
    return """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Terms of Service — Assistify Multi-Platform Poster</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #fff; color: #111; line-height: 1.7; }
  .container { max-width: 760px; margin: 0 auto; padding: 60px 24px; }
  h1 { font-size: 2rem; font-weight: 700; margin-bottom: 8px; }
  .updated { color: #888; font-size: 0.9rem; margin-bottom: 48px; }
  h2 { font-size: 1.15rem; font-weight: 600; margin: 36px 0 12px; }
  p, li { color: #444; margin-bottom: 12px; }
  ul { padding-left: 20px; }
  a { color: #111; }
</style>
</head>
<body>
<div class="container">
  <h1>Terms of Service</h1>
  <p class="updated">Last updated: April 2026 &mdash; Assistify, Freiburg im Breisgau</p>

  <h2>1. Acceptance of Terms</h2>
  <p>By using Assistify Multi-Platform Poster ("the Service"), you agree to these Terms of Service. The Service is an automated content publishing tool for Instagram, Facebook, and TikTok. Use is restricted to authorized account owners only.</p>

  <h2>2. Description of Service</h2>
  <p>Assistify Multi-Platform Poster enables automated scheduling and publishing of video content to social media platforms including Instagram, Facebook, and TikTok on behalf of the authorized account owner.</p>

  <h2>3. TikTok Integration</h2>
  <p>The Service integrates with the TikTok for Developers API. By authorizing this integration:</p>
  <ul>
    <li>You grant the Service permission to publish videos to your TikTok account on your behalf.</li>
    <li>You confirm you are the authorized owner of the TikTok account being connected.</li>
    <li>You agree to use this integration only for publishing lawful, original content.</li>
    <li>You agree not to use this Service for spam, mass automated interactions, or any violation of TikTok's Community Guidelines or Terms of Service.</li>
    <li>You acknowledge that all content published through this Service to your TikTok account is your sole responsibility.</li>
    <li>You may revoke TikTok access at any time via TikTok's account settings under "Connected Apps".</li>
  </ul>
  <p>This Service is not affiliated with, endorsed by, or sponsored by TikTok Inc. or ByteDance Ltd.</p>

  <h2>4. Permitted Use</h2>
  <p>You may use this Service only for lawful purposes and in accordance with all applicable platform terms of service (Meta, TikTok). You must not use the Service to post content that violates any applicable laws or platform policies.</p>

  <h2>5. Intellectual Property</h2>
  <p>You retain all rights to the content you publish through this Service. You grant the Service a limited license to transmit your content to the designated platforms solely for the purpose of fulfilling scheduled posts.</p>

  <h2>6. Disclaimer of Warranties</h2>
  <p>The Service is provided "as is" without warranties of any kind. We do not guarantee uninterrupted availability, particularly in cases of API changes by third-party platforms (Meta, TikTok).</p>

  <h2>7. Limitation of Liability</h2>
  <p>Assistify shall not be liable for any indirect, incidental, or consequential damages arising from the use of this Service. Liability is limited to the value of services rendered.</p>

  <h2>8. Governing Law</h2>
  <p>These Terms are governed by the laws of the Federal Republic of Germany. Place of jurisdiction is Freiburg im Breisgau.</p>

  <h2>9. Contact</h2>
  <p>Nabel Alsulaiman &mdash; Assistify<br>
  Email: <a href="mailto:assistifyai.yba@gmail.com">assistifyai.yba@gmail.com</a></p>
</div>
</body>
</html>"""

@app.route("/privacy")
def privacy():
    return """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Privacy Policy — Assistify Multi-Platform Poster</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #fff; color: #111; line-height: 1.7; }
  .container { max-width: 760px; margin: 0 auto; padding: 60px 24px; }
  h1 { font-size: 2rem; font-weight: 700; margin-bottom: 8px; }
  .updated { color: #888; font-size: 0.9rem; margin-bottom: 48px; }
  h2 { font-size: 1.15rem; font-weight: 600; margin: 36px 0 12px; }
  p, li { color: #444; margin-bottom: 12px; }
  ul { padding-left: 20px; }
  a { color: #111; }
</style>
</head>
<body>
<div class="container">
  <h1>Privacy Policy</h1>
  <p class="updated">Last updated: April 2026 &mdash; Assistify, Freiburg im Breisgau</p>

  <p>Assistify Multi-Platform Poster ("we", "the Service") is an automated social media scheduling tool that publishes video content to Instagram, Facebook, and TikTok on behalf of authorized account owners.</p>

  <h2>1. Data Controller</h2>
  <p>Nabel Alsulaiman, Sundgauallee 26, 79110 Freiburg im Breisgau, Germany.<br>
  Email: <a href="mailto:assistifyai.yba@gmail.com">assistifyai.yba@gmail.com</a></p>

  <h2>2. Information We Collect</h2>
  <ul>
    <li><strong>Account identifiers:</strong> Instagram User ID, Facebook Page ID, TikTok User ID.</li>
    <li><strong>Access tokens:</strong> OAuth tokens issued by Meta and TikTok to post on your behalf.</li>
    <li><strong>Video content:</strong> Videos you provide for scheduled posting, stored via Cloudinary.</li>
    <li><strong>Settings:</strong> Posting time preferences and caption configurations.</li>
  </ul>

  <h2>3. How We Use Your Data</h2>
  <p>We use collected data solely to authenticate with Instagram, Facebook, and TikTok on your behalf and to publish your scheduled videos. We do not sell, share, or use your data for advertising.</p>

  <h2>4. TikTok API — Data Access &amp; Usage</h2>
  <p>This Service integrates with the TikTok for Developers API to enable authorized users to schedule and publish video content on TikTok. This integration occurs only with your explicit authorization via TikTok's official OAuth 2.0 flow.</p>
  <p>TikTok permissions we request:</p>
  <ul>
    <li><strong>user.info.basic:</strong> To retrieve your TikTok display name for display within the Service.</li>
    <li><strong>video.publish:</strong> To publish videos to your TikTok account at your scheduled time.</li>
    <li><strong>video.upload:</strong> To upload video files to TikTok's servers for publishing.</li>
  </ul>
  <p>TikTok data we store:</p>
  <ul>
    <li>Your TikTok OAuth access token (stored securely as an environment variable, used only for posting)</li>
    <li>Video metadata such as title and privacy level (set by you)</li>
  </ul>
  <p>We do <strong>not</strong> read your TikTok messages, followers, comments, or analytics. We do not share TikTok data with third parties or use it for any purpose other than publishing your scheduled content.</p>
  <p>To revoke TikTok access, contact us or go to TikTok Settings &rarr; Security &rarr; Connected Apps and remove this Service. All stored tokens are immediately deleted upon revocation.</p>
  <p>This Service is not affiliated with TikTok Inc. or ByteDance Ltd. See <a href="https://www.tiktok.com/legal/privacy-policy" target="_blank">TikTok's Privacy Policy</a> for details on how TikTok handles your data.</p>

  <h2>5. Facebook &amp; Instagram Data</h2>
  <p>We access instagram_content_publish, pages_manage_posts, pages_show_list, and pages_read_engagement permissions — the minimum required for scheduling and publishing. We do not access messages, contacts, or personal profile data beyond what is needed for posting.</p>

  <h2>6. Data Retention &amp; Security</h2>
  <p>Access tokens are stored securely as environment variables on Railway's infrastructure. Videos are stored on Cloudinary. You can request deletion of all your data by contacting us at the email below.</p>

  <h2>7. Your Rights</h2>
  <ul>
    <li>Right to access the data we hold about you</li>
    <li>Right to request deletion of your data</li>
    <li>Right to revoke platform access at any time</li>
  </ul>

  <h2>8. Third-Party Services</h2>
  <ul>
    <li><strong>TikTok API</strong> &mdash; content publishing</li>
    <li><strong>Meta (Facebook/Instagram Graph API)</strong> &mdash; content publishing</li>
    <li><strong>Cloudinary</strong> &mdash; video storage</li>
    <li><strong>Railway</strong> &mdash; hosting &amp; infrastructure</li>
    <li><strong>Anthropic Claude</strong> &mdash; AI caption generation (optional)</li>
  </ul>

  <h2>9. Contact</h2>
  <p>Nabel Alsulaiman &mdash; Assistify<br>
  Email: <a href="mailto:assistifyai.yba@gmail.com">assistifyai.yba@gmail.com</a></p>

  <h2>10. Changes</h2>
  <p>We may update this Privacy Policy. Changes will be reflected by updating the date at the top of this page.</p>
</div>
</body>
</html>"""

@app.route("/debug_tiktok")
def debug_tiktok():
    if not TIKTOK_TOKEN:
        return jsonify({"error": "Kein Token"})
    r = requests.get(
        "https://open.tiktokapis.com/v2/user/info/",
        headers={"Authorization": f"Bearer {TIKTOK_TOKEN}"},
        params={"fields": "open_id,display_name,avatar_url"}
    )
    return jsonify({"status": r.status_code, "response": r.json()})

@app.route("/tiktok/auth")
def tiktok_auth():
    import urllib.parse
    params = {
        "client_key": TIKTOK_CLIENT_KEY,
        "scope": "user.info.basic,video.publish,video.upload",
        "response_type": "code",
        "redirect_uri": "https://web-production-c56a1.up.railway.app/tiktok/callback",
        "state": "assistify123",
    }
    url = "https://www.tiktok.com/v2/auth/authorize/?" + urllib.parse.urlencode(params)
    return f'<a href="{url}">Login mit TikTok</a>'

@app.route("/tiktok/callback")
def tiktok_callback():
    from flask import request as freq
    code = freq.args.get("code")
    if not code:
        return jsonify({"error": "Kein Code erhalten", "params": dict(freq.args)})
    r = requests.post("https://open.tiktokapis.com/v2/oauth/token/", data={
        "client_key": TIKTOK_CLIENT_KEY,
        "client_secret": TIKTOK_CLIENT_SECRET,
        "code": code,
        "grant_type": "authorization_code",
        "redirect_uri": "https://web-production-c56a1.up.railway.app/tiktok/callback",
    })
    data = r.json()
    token = data.get("access_token", "")
    print(f"TikTok Access Token: {token}")
    return jsonify({"access_token": token, "full_response": data})

# ─── Scheduler ────────────────────────────────────────────────────────────────
scheduler = BackgroundScheduler(timezone=BERLIN)
scheduler.add_job(daily_post, CronTrigger(hour=19, minute=0, timezone=BERLIN))       # Queue 1 — 19:00 Freiburg
scheduler.add_job(daily_post_noon, CronTrigger(hour=12, minute=0, timezone=BERLIN))  # Queue 2 — 12:00 Abu Dhabi
scheduler.add_job(daily_post_evening, CronTrigger(hour=20, minute=0, timezone=BERLIN))  # Queue 3 — 20:00 Storytelling
scheduler.start()

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8080))
    print(f"Multi-Platform Poster läuft | Port {port} | täglich 19:00 Berlin")
    app.run(host="0.0.0.0", port=port)
